### ISSUE TITLE
Setup failed for maxcube: Component failed to initialize.

### ISSUE THREAD

**Issue by vpomax** [Bouni/max-cube-protocol#44]
My eQ-3 Max!|Cube works fine
but if I try to connect with my Home Assistant v. 0.80.3 with Hassio it give me the following error:

ERROR (MainThread) [homeassistant.setup] Setup failed for maxcube: Component failed to initialize.

I put in configuration.yaml

```
maxcube:
  gateways:
    - host: 192.168.1.222
      port: 62910
```

What's wrong?
